### ISSUE TITLE
Update Tests

### ISSUE THREAD

**Issue by Stepandanci** [Maks027/Banking#2]
You wrote a good test task and completed all the points.
You should write a test that checks the data from demo provider bendigo bank.

1. Take HTML from bendigo bank and save it in a file (check screenshot).
`html_example = Nokogiri::HTML(File.read('accounts.html'))`

![Снимок](https://user-images.githubusercontent.com/29861352/84526427-f2d8bc80-ace5-11ea-81e2-b36cf686705d.PNG)

2. Call method for parse accounts and send HTML data. `parse_accounts(html_example)`

3. Check the number of accounts and show an example account in a hash format.

Example:
```ruby
it 'check number of accounts and show an example account' do
  html_example = Nokogiri::HTML(File.read('accounts.html'))
  accounts = parse_accounts(html_example) # NOTE: It is my example, not a real code.

  expect(accounts.count).to eq(5)
  expect(accounts.first.to_hash).to eq(
    {
      "name"         => "Demo Everyday Account",
      "currency"     => "USD",
      "balance"      => 1959.90,
      "nature"       => "account",
      "transactions" => []
    }
  )
end
```

4. Do the same for transactions.

Good luck!

**Comment by Maks027** [comment]
Thank you for feedback!
Ok, I will complete the task asap. Actually, I thought about tests like
that, but implemented just the basic , as I was not sure if it is relevant.

**Comment by Maks027** [comment]
Hi!
I added the required tests. Also, I modified account data parsing methods to get data directly from the list (the one you showed in the screenshot) at the start. Then, the script clicks on each list element to get transactions  data. That way, all parsing methods use just css selectors, which I guess I should have done right from the start. That way, I actually was able to write the required tests.

**Comment by Stepandanci** [comment]
**Congratulations**!
You have completed the test task perfectly.
You understand what needs to be done and made it in your style.

I will ask HR to invite you to the second interview.

**Comment by Maks027** [comment]
Great! Thank you!
May I ask you for a favor if its not too hard for you? Can you give me some
tips about the interview, so I could prepare a little? Not in details, just
some general topics that came first to your mind.

**Comment by Stepandanci** [comment]
You have all the necessary knowledge.
You are ready.
